# Generated by Django 3.2.7 on 2021-10-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='zip',
            field=models.SmallIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
